version: '3.8'

services:
  backend:
    image: manyin-server
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/build
      - /build/node_modules
    env_file:
      - ./config/config.env
