export const ADMIN_CHECK_REQUEST = "ADMIN_CHECK_REQUEST";
export const ADMIN_CHECK_SUCCESS = "ADMIN_CHECK_SUCCESS";
export const ADMIN_CHECK_FAILURE = "ADMIN_CHECK_FAILURE";


export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";


export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAILURE = "ALL_ORDERS_FAILURE";


export const DELETE_ANY_ORDER_REQUEST = "DELETE_ANY_ORDER_REQUEST";
export const DELETE_ANY_ORDER_SUCCESS = "DELETE_ANY_ORDER_SUCCESS";
export const DELETE_ANY_ORDER_FAILURE = "DELETE_ANY_ORDER_FAILURE";


export const CANCEL_ANY_ORDER_REQUEST = "CANCEL_ANY_ORDER_REQUEST";
export const CANCEL_ANY_ORDER_SUCCESS = "CANCEL_ANY_ORDER_SUCCESS";
export const CANCEL_ANY_ORDER_FAILURE = "CANCEL_ANY_ORDER_FAILURE";
export const DELETE_CANCEL_ANY_ORDER_RESET = "DELETE_CANCEL_ANY_ORDER_RESET";