export const ADMIN_CHECK_REQUEST = "ADMIN_CHECK_REQUEST";
export const ADMIN_CHECK_SUCCESS = "ADMIN_CHECK_SUCCESS";
export const ADMIN_CHECK_FAILURE = "ADMIN_CHECK_FAILURE";


export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";