export const ADMIN_CHECK_REQUEST = "ADMIN_CHECK_REQUEST";
export const ADMIN_CHECK_SUCCESS = "ADMIN_CHECK_SUCCESS";
export const ADMIN_CHECK_FAILURE = "ADMIN_CHECK_FAILURE";


export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";


export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
export const ALL_ORDERS_FAILURE = "ALL_ORDERS_FAILURE";


export const DELETE_ANY_ORDER_REQUEST = "DELETE_ANY_ORDER_REQUEST";
export const DELETE_ANY_ORDER_SUCCESS = "DELETE_ANY_ORDER_SUCCESS";
export const DELETE_ANY_ORDER_FAILURE = "DELETE_ANY_ORDER_FAILURE";


export const UPDATE_ANY_ORDER_STATUS_REQUEST = "UPDATE_ANY_ORDER_STATUS_REQUEST";
export const UPDATE_ANY_ORDER_STATUS_SUCCESS = "UPDATE_ANY_ORDER_STATUS_SUCCESS";
export const UPDATE_ANY_ORDER_STATUS_FAILURE = "UPDATE_ANY_ORDER_STATUS_FAILURE";
export const DELETE_UPDATE_ANY_ORDER_RESET = "DELETE_UPDATE_ANY_ORDER_RESET";


export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAILURE = "ALL_USERS_FAILURE";


export const ALL_SELLERS_REQUEST = "ALL_SELLERS_REQUEST";
export const ALL_SELLERS_SUCCESS = "ALL_SELLERS_SUCCESS";
export const ALL_SELLERS_FAILURE = "ALL_SELLERS_FAILURE";


export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
export const DELETE_USER_RESET = "DELETE_USER_RESET";


export const UPDATE_USER_ROLE_REQUEST = "UPDATE_USER_ROLE_REQUEST";
export const UPDATE_USER_ROLE_SUCCESS = "UPDATE_USER_ROLE_SUCCESS";
export const UPDATE_USER_ROLE_FAILURE = "UPDATE_USER_ROLE_FAILURE";
export const UPDATE_USER_ROLE_RESET = "UPDATE_USER_ROLE_RESET";