
export const ADD_TO_CART = "ADD_TO_CART";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";

export const ORDER_VALUE_REQUEST = "ORDER_VALUE_REQUEST";
export const ORDER_VALUE_SUCCESS = "ORDER_VALUE_SUCCESS";
export const ORDER_VALUE_FAILURE = "ORDER_VALUE_FAILURE";