
export const ADD_TO_CART = "ADD_TO_CART";
export const RESET_CART_ITEMS = "RESET_CART_ITEMS";

export const ORDER_VALUE_REQUEST = "ORDER_VALUE_REQUEST";
export const ORDER_VALUE_SUCCESS = "ORDER_VALUE_SUCCESS";
export const ORDER_VALUE_FAILURE = "ORDER_VALUE_FAILURE";