
export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAILURE = "ALL_PRODUCT_FAILURE";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILURE = "PRODUCT_DETAILS_FAILURE";

export const SELLER_PRODUCT_REQUEST = "SELLER_PRODUCT_REQUEST";
export const SELLER_PRODUCT_SUCCESS = "SELLER_PRODUCT_SUCCESS";
export const SELLER_PRODUCT_FAILURE = "SELLER_PRODUCT_FAILURE";

export const BUNDLE_PRODUCTS_REQUEST = "BUNDLE_PRODUCTS_REQUEST";
export const BUNDLE_PRODUCTS_SUCCESS = "BUNDLE_PRODUCTS_SUCCESS";
export const BUNDLE_PRODUCTS_FAILURE = "BUNDLE_PRODUCTS_FAILURE";