export const SELLER_CHECK_REQUEST = "SELLER_CHECK_REQUEST";
export const SELLER_CHECK_SUCCESS = "SELLER_CHECK_SUCCESS";
export const SELLER_CHECK_FAILURE = "SELLER_CHECK_FAILURE";

export const SELLER_DATA_ANALYSIS_SUCCESS = "SELLER_DATA_ANALYSIS_SUCCESS";
export const SELLER_DATA_ANALYSIS_REQUEST = "SELLER_DATA_ANALYSIS_REQUEST";
export const SELLER_DATA_ANALYSIS_FAILURE = "SELLER_DATA_ANALYSIS_FAILURE";
